### ISSUE TITLE
vivo刘海屏手机设置成FULL_SCREEN不适配

### ISSUE THREAD

**Issue by youlongsam** [wcl9900/NotchFit#2]
NotchScreenType设置成FULL_SCREEN，在oppo刘海屏手机上是全屏适配的，在vivo刘海屏的手机上刘海屏会存在黑边

**Comment by wcl9900** [comment]
oppo手机默认开启刘海区域使用，vivo没有默认开启，这属于手机自身差异导致，所以vivo会出现黑边，vivo需要用户在设置中手动开启刘海区域的使用才能不出现黑边
